import type { StockInfo } from './types';

export const NIFTY_50: StockInfo[] = [
  { symbol: 'RELIANCE.NS', name: 'Reliance Industries', exchange: 'NSE', market: 'IN' },
  { symbol: 'TCS.NS', name: 'Tata Consultancy Services', exchange: 'NSE', market: 'IN' },
  { symbol: 'HDFCBANK.NS', name: 'HDFC Bank', exchange: 'NSE', market: 'IN' },
  { symbol: 'INFY.NS', name: 'Infosys', exchange: 'NSE', market: 'IN' },
  { symbol: 'ICICIBANK.NS', name: 'ICICI Bank', exchange: 'NSE', market: 'IN' },
  { symbol: 'HINDUNILVR.NS', name: 'Hindustan Unilever', exchange: 'NSE', market: 'IN' },
  { symbol: 'ITC.NS', name: 'ITC', exchange: 'NSE', market: 'IN' },
  { symbol: 'SBIN.NS', name: 'State Bank of India', exchange: 'NSE', market: 'IN' },
  { symbol: 'BHARTIARTL.NS', name: 'Bharti Airtel', exchange: 'NSE', market: 'IN' },
  { symbol: 'KOTAKBANK.NS', name: 'Kotak Mahindra Bank', exchange: 'NSE', market: 'IN' },
  { symbol: 'LT.NS', name: 'Larsen & Toubro', exchange: 'NSE', market: 'IN' },
  { symbol: 'AXISBANK.NS', name: 'Axis Bank', exchange: 'NSE', market: 'IN' },
  { symbol: 'ASIANPAINT.NS', name: 'Asian Paints', exchange: 'NSE', market: 'IN' },
  { symbol: 'MARUTI.NS', name: 'Maruti Suzuki', exchange: 'NSE', market: 'IN' },
  { symbol: 'TITAN.NS', name: 'Titan Company', exchange: 'NSE', market: 'IN' },
  { symbol: 'SUNPHARMA.NS', name: 'Sun Pharma', exchange: 'NSE', market: 'IN' },
  { symbol: 'BAJFINANCE.NS', name: 'Bajaj Finance', exchange: 'NSE', market: 'IN' },
  { symbol: 'WIPRO.NS', name: 'Wipro', exchange: 'NSE', market: 'IN' },
  { symbol: 'HCLTECH.NS', name: 'HCL Technologies', exchange: 'NSE', market: 'IN' },
  { symbol: 'ULTRACEMCO.NS', name: 'UltraTech Cement', exchange: 'NSE', market: 'IN' },
  { symbol: 'ONGC.NS', name: 'ONGC', exchange: 'NSE', market: 'IN' },
  { symbol: 'NTPC.NS', name: 'NTPC', exchange: 'NSE', market: 'IN' },
  { symbol: 'TATAMOTORS.NS', name: 'Tata Motors', exchange: 'NSE', market: 'IN' },
  { symbol: 'POWERGRID.NS', name: 'Power Grid Corp', exchange: 'NSE', market: 'IN' },
  { symbol: 'M&M.NS', name: 'Mahindra & Mahindra', exchange: 'NSE', market: 'IN' },
  { symbol: 'JSWSTEEL.NS', name: 'JSW Steel', exchange: 'NSE', market: 'IN' },
  { symbol: 'TATASTEEL.NS', name: 'Tata Steel', exchange: 'NSE', market: 'IN' },
  { symbol: 'ADANIENT.NS', name: 'Adani Enterprises', exchange: 'NSE', market: 'IN' },
  { symbol: 'ADANIPORTS.NS', name: 'Adani Ports', exchange: 'NSE', market: 'IN' },
  { symbol: 'COALINDIA.NS', name: 'Coal India', exchange: 'NSE', market: 'IN' },
  { symbol: 'BAJAJFINSV.NS', name: 'Bajaj Finserv', exchange: 'NSE', market: 'IN' },
  { symbol: 'TECHM.NS', name: 'Tech Mahindra', exchange: 'NSE', market: 'IN' },
  { symbol: 'HDFCLIFE.NS', name: 'HDFC Life', exchange: 'NSE', market: 'IN' },
  { symbol: 'SBILIFE.NS', name: 'SBI Life Insurance', exchange: 'NSE', market: 'IN' },
  { symbol: 'GRASIM.NS', name: 'Grasim Industries', exchange: 'NSE', market: 'IN' },
  { symbol: 'DIVISLAB.NS', name: "Divi's Laboratories", exchange: 'NSE', market: 'IN' },
  { symbol: 'INDUSINDBK.NS', name: 'IndusInd Bank', exchange: 'NSE', market: 'IN' },
  { symbol: 'NESTLEIND.NS', name: 'Nestle India', exchange: 'NSE', market: 'IN' },
  { symbol: 'BRITANNIA.NS', name: 'Britannia Industries', exchange: 'NSE', market: 'IN' },
  { symbol: 'CIPLA.NS', name: 'Cipla', exchange: 'NSE', market: 'IN' },
  { symbol: 'DRREDDY.NS', name: "Dr. Reddy's Labs", exchange: 'NSE', market: 'IN' },
  { symbol: 'EICHERMOT.NS', name: 'Eicher Motors', exchange: 'NSE', market: 'IN' },
  { symbol: 'APOLLOHOSP.NS', name: 'Apollo Hospitals', exchange: 'NSE', market: 'IN' },
  { symbol: 'HEROMOTOCO.NS', name: 'Hero MotoCorp', exchange: 'NSE', market: 'IN' },
  { symbol: 'BPCL.NS', name: 'BPCL', exchange: 'NSE', market: 'IN' },
  { symbol: 'TATACONSUM.NS', name: 'Tata Consumer', exchange: 'NSE', market: 'IN' },
  { symbol: 'HINDALCO.NS', name: 'Hindalco', exchange: 'NSE', market: 'IN' },
  { symbol: 'LTIM.NS', name: 'LTIMindtree', exchange: 'NSE', market: 'IN' },
  { symbol: 'BAJAJ-AUTO.NS', name: 'Bajaj Auto', exchange: 'NSE', market: 'IN' },
  { symbol: 'SHRIRAMFIN.NS', name: 'Shriram Finance', exchange: 'NSE', market: 'IN' },
];

export const SP500_TOP_50: StockInfo[] = [
  { symbol: 'AAPL', name: 'Apple', exchange: 'NASDAQ', market: 'US' },
  { symbol: 'MSFT', name: 'Microsoft', exchange: 'NASDAQ', market: 'US' },
  { symbol: 'GOOGL', name: 'Alphabet (Google)', exchange: 'NASDAQ', market: 'US' },
  { symbol: 'AMZN', name: 'Amazon', exchange: 'NASDAQ', market: 'US' },
  { symbol: 'NVDA', name: 'NVIDIA', exchange: 'NASDAQ', market: 'US' },
  { symbol: 'META', name: 'Meta Platforms', exchange: 'NASDAQ', market: 'US' },
  { symbol: 'TSLA', name: 'Tesla', exchange: 'NASDAQ', market: 'US' },
  { symbol: 'BRK-B', name: 'Berkshire Hathaway', exchange: 'NYSE', market: 'US' },
  { symbol: 'JPM', name: 'JPMorgan Chase', exchange: 'NYSE', market: 'US' },
  { symbol: 'V', name: 'Visa', exchange: 'NYSE', market: 'US' },
  { symbol: 'UNH', name: 'UnitedHealth', exchange: 'NYSE', market: 'US' },
  { symbol: 'MA', name: 'Mastercard', exchange: 'NYSE', market: 'US' },
  { symbol: 'JNJ', name: 'Johnson & Johnson', exchange: 'NYSE', market: 'US' },
  { symbol: 'HD', name: 'Home Depot', exchange: 'NYSE', market: 'US' },
  { symbol: 'PG', name: 'Procter & Gamble', exchange: 'NYSE', market: 'US' },
  { symbol: 'XOM', name: 'ExxonMobil', exchange: 'NYSE', market: 'US' },
  { symbol: 'AVGO', name: 'Broadcom', exchange: 'NASDAQ', market: 'US' },
  { symbol: 'COST', name: 'Costco', exchange: 'NASDAQ', market: 'US' },
  { symbol: 'MRK', name: 'Merck', exchange: 'NYSE', market: 'US' },
  { symbol: 'ABBV', name: 'AbbVie', exchange: 'NYSE', market: 'US' },
  { symbol: 'CVX', name: 'Chevron', exchange: 'NYSE', market: 'US' },
  { symbol: 'CRM', name: 'Salesforce', exchange: 'NYSE', market: 'US' },
  { symbol: 'KO', name: 'Coca-Cola', exchange: 'NYSE', market: 'US' },
  { symbol: 'PEP', name: 'PepsiCo', exchange: 'NASDAQ', market: 'US' },
  { symbol: 'ADBE', name: 'Adobe', exchange: 'NASDAQ', market: 'US' },
  { symbol: 'WMT', name: 'Walmart', exchange: 'NYSE', market: 'US' },
  { symbol: 'BAC', name: 'Bank of America', exchange: 'NYSE', market: 'US' },
  { symbol: 'MCD', name: "McDonald's", exchange: 'NYSE', market: 'US' },
  { symbol: 'CSCO', name: 'Cisco', exchange: 'NASDAQ', market: 'US' },
  { symbol: 'NFLX', name: 'Netflix', exchange: 'NASDAQ', market: 'US' },
  { symbol: 'AMD', name: 'AMD', exchange: 'NASDAQ', market: 'US' },
  { symbol: 'TMO', name: 'Thermo Fisher', exchange: 'NYSE', market: 'US' },
  { symbol: 'INTC', name: 'Intel', exchange: 'NASDAQ', market: 'US' },
  { symbol: 'DIS', name: 'Walt Disney', exchange: 'NYSE', market: 'US' },
  { symbol: 'ABT', name: 'Abbott Labs', exchange: 'NYSE', market: 'US' },
  { symbol: 'ORCL', name: 'Oracle', exchange: 'NYSE', market: 'US' },
  { symbol: 'QCOM', name: 'Qualcomm', exchange: 'NASDAQ', market: 'US' },
  { symbol: 'INTU', name: 'Intuit', exchange: 'NASDAQ', market: 'US' },
  { symbol: 'TXN', name: 'Texas Instruments', exchange: 'NASDAQ', market: 'US' },
  { symbol: 'PM', name: 'Philip Morris', exchange: 'NYSE', market: 'US' },
  { symbol: 'CMCSA', name: 'Comcast', exchange: 'NASDAQ', market: 'US' },
  { symbol: 'NKE', name: 'Nike', exchange: 'NYSE', market: 'US' },
  { symbol: 'DHR', name: 'Danaher', exchange: 'NYSE', market: 'US' },
  { symbol: 'NEE', name: 'NextEra Energy', exchange: 'NYSE', market: 'US' },
  { symbol: 'RTX', name: 'RTX (Raytheon)', exchange: 'NYSE', market: 'US' },
  { symbol: 'BMY', name: 'Bristol-Myers Squibb', exchange: 'NYSE', market: 'US' },
  { symbol: 'SPGI', name: 'S&P Global', exchange: 'NYSE', market: 'US' },
  { symbol: 'HON', name: 'Honeywell', exchange: 'NASDAQ', market: 'US' },
  { symbol: 'UPS', name: 'UPS', exchange: 'NYSE', market: 'US' },
  { symbol: 'LIN', name: 'Linde', exchange: 'NASDAQ', market: 'US' },
];

export const ALL_STOCKS: StockInfo[] = [...NIFTY_50, ...SP500_TOP_50];
